# Generated by Django 5.0.2 on 2024-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotalog', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'verbose_name': 'Фотография растения', 'verbose_name_plural': 'Фотографии растения'},
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Фотография'),
        ),
    ]
