# Generated by Django 5.0.2 on 2024-02-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotalog', '0004_alter_plantimage_options_rename_slag_plant_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время первичного создания сущности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновление сущности')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фотография')),
                ('undertitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='Подпись фотографии')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cotalog.plant', verbose_name='Растения')),
            ],
            options={
                'verbose_name': 'Фотография растения',
                'verbose_name_plural': 'Фотографии растения',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время первичного создания сущности')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновление сущности')),
                ('title', models.CharField(max_length=256, verbose_name='Название вида растения (Лилия, Георгины, Гладиолус)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varieries', to='cotalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Разновидность растения',
                'verbose_name_plural': 'Разновидности растений',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='cotalog.variety', verbose_name='Разновидность'),
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
