# Generated by Django 5.0.2 on 2024-02-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotalog', '0005_remove_plant_category_image_variety_plant_variety_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['title'], 'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['title'], 'verbose_name': 'Разновидность растения', 'verbose_name_plural': 'Разновидности растений'},
        ),
    ]
